[project]
name = "ndbc_buoy_scraper"
version = "0.1.0"
description = "A web scraper for NDBC buoy data using Scrapy."
readme = "README.md"
license = "MIT"
license-files = ["LICENSE"]
requires-python = ">=3.13"
dependencies = [
    "duckdb>=1.1.0",
    "pandas>=3.0.2",
    "pyarrow>=18.0.0",
    "python-dotenv>=1.2.3",
    "scrapy>=2.15.1",
]

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]
